# Generated by Django 5.0.1 on 2024-01-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='roll_number',
            new_name='sub',
        ),
    ]
